before_script:
    - ./bootstrap.sh

stages:
    - build
    - test

build:
    stage: build
    script:
        - ./configure
        - make

check:
    stage: test
    script:
        - ./configure --enable-coverage
        - make coverage | tail -10
